import { z } from "zod";
import { analyticsId, normalizeAnalyticsPath, normalizeReferrerHost, normalizeUtm } from "./contract";

export const VISITOR_KEY = "deutschmit_analytics_visitor_v2";
export const SESSION_KEY = "deutschmit_analytics_session_v2";
export const QUIZ_KEY = "deutschmit_analytics_quiz_v2";
export const SESSION_TIMEOUT = 30 * 60_000;
export const VISITOR_TTL = 90 * 86_400_000;
const trafficSchema = z.object({
  entry_path: z.string().transform(normalizeAnalyticsPath),
  referrer_host: z.string().transform(normalizeReferrerHost).optional(),
  utm_source: z.string().transform(value => normalizeUtm(value, "source")).optional(),
  utm_medium: z.string().transform(value => normalizeUtm(value, "medium")).optional(),
  utm_campaign: z.string().transform(value => normalizeUtm(value, "campaign")).optional(),
}).strict();
export type Traffic = z.output<typeof trafficSchema>;
const visitorSchema = z.object({ id: analyticsId, created: z.number().nonnegative() }).strict();
const sessionSchema = z.object({ id: analyticsId, visitor: analyticsId, lastActivity: z.number().nonnegative(), sequence: z.number().int().nonnegative().max(2147483640), traffic: trafficSchema, documentTimeOrigin: z.number().nonnegative().optional() }).strict();
export type Session = z.output<typeof sessionSchema>;

export function readTraffic(): Traffic {
  const url = new URL(window.location.href);
  let referrer: string | undefined;
  try {
    const source = document.referrer ? new URL(document.referrer) : null;
    if (source && source.hostname !== url.hostname) referrer = normalizeReferrerHost(source.hostname);
  } catch { referrer = "unknown"; }
  return {
    entry_path: normalizeAnalyticsPath(url.pathname), referrer_host: referrer,
    utm_source: normalizeUtm(url.searchParams.get("utm_source") ?? undefined, "source"),
    utm_medium: normalizeUtm(url.searchParams.get("utm_medium") ?? undefined, "medium"),
    utm_campaign: normalizeUtm(url.searchParams.get("utm_campaign") ?? undefined, "campaign"),
  };
}

function readJson(storage: Storage, key: string): unknown {
  try { return JSON.parse(storage.getItem(key) ?? "null"); } catch { return null; }
}

export function clearAnalyticsIdentity() {
  try { localStorage.removeItem(VISITOR_KEY); } catch {}
  try { sessionStorage.removeItem(SESSION_KEY); } catch {}
  try { sessionStorage.removeItem(QUIZ_KEY); } catch {}
}

export function isCurrentVisitor(id: string | null): boolean {
  try {
    const saved = visitorSchema.safeParse(readJson(localStorage, VISITOR_KEY));
    return saved.success && saved.data.id === id && Date.now() >= saved.data.created && Date.now() - saved.data.created < VISITOR_TTL;
  } catch { return false; }
}

export class AnalyticsIdentity {
  session: Session | null = null;
  private release?: () => void;
  private stopped = false;

  constructor(private allowed: () => boolean) {}

  async initialize(): Promise<boolean> {
    try {
      if (!this.allowed() || this.stopped) return false;
      // Fail closed when persistence is blocked. No identifier is generated by this probe.
      sessionStorage.setItem(SESSION_KEY + "_probe", "1");
      sessionStorage.removeItem(SESSION_KEY + "_probe");
      localStorage.setItem(VISITOR_KEY + "_probe", "1");
      localStorage.removeItem(VISITOR_KEY + "_probe");
      const loadVisitor = () => {
        if (!this.allowed() || this.stopped) return null;
        const saved = visitorSchema.safeParse(readJson(localStorage, VISITOR_KEY));
        const now = Date.now();
        const visitor = saved.success && saved.data.created <= now && now - saved.data.created < VISITOR_TTL
          ? saved.data : { id: crypto.randomUUID(), created: now };
        localStorage.setItem(VISITOR_KEY, JSON.stringify(visitor));
        return visitor;
      };
      const visitor = navigator.locks ? await navigator.locks.request("deutschmit-analytics-visitor", loadVisitor) : loadVisitor();
      if (!visitor || !this.allowed() || this.stopped) return false;
      const saved = sessionSchema.safeParse(readJson(sessionStorage, SESSION_KEY));
      const navigation = performance.getEntriesByType("navigation")[0] as PerformanceNavigationTiming | undefined;
      const activation = (window as Window & { navigation?: { activation?: { from: unknown | null } } }).navigation?.activation;
      // A free lock cannot establish tab ownership: sessionStorage may have been copied
      // after the opener stopped tracking. Initial/duplicated tabs have no activation.from.
      // timeOrigin also permits tracker restarts within the document (including BFCache).
      const sameDocument = saved.success && saved.data.documentTimeOrigin === performance.timeOrigin;
      const continuingTab = sameDocument || (activation ? activation.from !== null : navigation?.type === "reload" || navigation?.type === "back_forward");
      let session = saved.success && saved.data.visitor === visitor.id && saved.data.lastActivity <= Date.now() && Date.now() - saved.data.lastActivity < SESSION_TIMEOUT
        && continuingTab ? saved.data : null;
      if (session) {
        if (navigator.locks) {
          if (!await this.claim(session.id)) session = null;
        }
      }
      if (!this.allowed() || this.stopped) return false;
      if (!session) {
        session = { id: crypto.randomUUID(), visitor: visitor.id, lastActivity: Date.now(), sequence: 0, traffic: readTraffic() };
        if (navigator.locks && !await this.claim(session.id)) return false;
      }
      if (!this.allowed() || this.stopped) return false;
      this.session = session;
      this.session.documentTimeOrigin = performance.timeOrigin;
      this.save();
      return true;
    } catch { this.stop(); return false; }
  }

  private claim(id: string): Promise<boolean> {
    return new Promise(resolve => {
      void navigator.locks.request(`deutschmit-analytics-session-${id}`, { ifAvailable: true }, lock => {
        if (!lock || this.stopped) { resolve(false); return; }
        return new Promise<void>(release => { this.release = release; resolve(true); });
      }).catch(() => resolve(false));
    });
  }

  currentVisitor(): boolean {
    return isCurrentVisitor(this.session?.visitor ?? null);
  }

  save() { if (this.session) sessionStorage.setItem(SESSION_KEY, JSON.stringify(this.session)); }
  stop() { this.stopped = true; this.release?.(); this.release = undefined; this.session = null; }
}
