FROM node:20-alpine AS base

WORKDIR /app

FROM base AS deps

COPY package*.json ./
RUN npm ci

FROM deps AS development

ENV NODE_ENV=development

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]

FROM deps AS builder

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_TELEGRAM_BOT_URL
ARG NEXT_PUBLIC_TELEGRAM_CHANNEL_URL
ARG NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE=off
ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_TELEGRAM_BOT_URL=${NEXT_PUBLIC_TELEGRAM_BOT_URL}
ENV NEXT_PUBLIC_TELEGRAM_CHANNEL_URL=${NEXT_PUBLIC_TELEGRAM_CHANNEL_URL}
ENV NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL=${NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_CONTACT_EMAIL=${NEXT_PUBLIC_CONTACT_EMAIL}
ENV NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE=${NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE}

RUN case "$NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE" in off|new|legacy) ;; *) echo "Invalid website analytics mode" >&2; exit 1 ;; esac

COPY . .

RUN npm run build

FROM base AS production-deps

COPY package*.json ./
RUN npm ci --omit=dev

FROM base AS production

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_TELEGRAM_BOT_URL
ARG NEXT_PUBLIC_TELEGRAM_CHANNEL_URL
ARG NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE=off
LABEL de.deutschmit.analytics-mode=${NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE}
ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_TELEGRAM_BOT_URL=${NEXT_PUBLIC_TELEGRAM_BOT_URL}
ENV NEXT_PUBLIC_TELEGRAM_CHANNEL_URL=${NEXT_PUBLIC_TELEGRAM_CHANNEL_URL}
ENV NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL=${NEXT_PUBLIC_DEUTSCH_TRAINER_BOT_URL}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_CONTACT_EMAIL=${NEXT_PUBLIC_CONTACT_EMAIL}
ENV NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE=${NEXT_PUBLIC_WEBSITE_ANALYTICS_MODE}

COPY --from=production-deps /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/db/migrations ./db/migrations

EXPOSE 3000
CMD ["npm", "run", "start", "--", "-H", "0.0.0.0", "-p", "3000"]
